main: me.fluglow.InvisibilityPlus
name: Invisibility+
version: 1.3
author: Fluglow
description: Hides various visual effects of invisible players.
depend: [ProtocolLib]
permissions:
  invisiblearmor.invisible:
    description: Deprecated. Allows the player to be affected by this plugin.
    default: true
  invisibilityplus.invisible:
    description: Allows the player to be affected by this plugin.
    default: true